### ISSUE TITLE
check if user is offline

### ISSUE THREAD

**Issue by darkpanda08** [darkpanda08/cryptocurlive-cli#2]
Before sending the request to API first check if the user is connected to the internet and display the message if offline.

**Comment by abraaoduarte** [comment]
I can help with this task

**Comment by darkpanda08** [comment]
Okay. Please go on with this.

**Comment by abraaoduarte** [comment]
Check my PR #3

**Comment by darkpanda08** [comment]
Thanks for the PR. I have reviewed the changes everything looks good to me.
